import { ProductCategory } from "./enums";
import { getImageUrl } from "./functions";
import { Product } from "./types";

/**
 * LIST OF CATEGORIES BRANDS
 */
export const brands: Record<ProductCategory, string[]> = {
  [ProductCategory.PHONE]: ["Apple", "Samsung", "Huawei"],
  [ProductCategory.MOTORCYCLE]: ["Yamaha", "Honda", "Suzuki", "Kawasaki"],
  [ProductCategory.LOAN]: ["Banco de Chile", "Banco Estado", "Banco Santander"],
  [ProductCategory.STORE]: ["Falabella", "Paris", "Liverpool"],
  [ProductCategory.TRACKING]: ["Correos de Chile", "Chilexpress"],
  [ProductCategory.CLUB]: ["Cencosud", "Paris", "Liverpool"],
};

/**
 * LIST OF PRODUCTS FOR THE HOME PAGE
 */

export const productList: Product[] = [
  // Phones
  {
    id: "1",
    name: "iPhone 13",
    brand: "Apple",
    reviews: 5,
    originalPrice: 1000,
    currentPrice: 900,
    image: getImageUrl("1"),
    category: ProductCategory.PHONE,
    discount: 10,
  },
  {
    id: "2",
    name: "Galaxy S22",
    brand: "Samsung",
    reviews: 4,
    originalPrice: 950,
    currentPrice: 800,
    image: getImageUrl("2"),
    category: ProductCategory.PHONE,
    discount: 40,
  },
  {
    id: "3",
    name: "P50 Pro",
    brand: "Huawei",
    reviews: 3,
    originalPrice: 900,
    currentPrice: 750,
    image: getImageUrl("3"),
    category: ProductCategory.PHONE,
    discount: 30,
  },
  {
    id: "33",
    name: "P50 Pro Max",
    brand: "Huawei",
    reviews: 2,
    originalPrice: 920,
    currentPrice: 790,
    image: getImageUrl("33"),
    category: ProductCategory.PHONE,
    discount: 45,
  },
  // Motorcycles
  {
    id: "4",
    name: "YZF-R1",
    brand: "Yamaha",
    reviews: 5,
    originalPrice: 20000,
    currentPrice: 19000,
    image: getImageUrl("4"),
    category: ProductCategory.MOTORCYCLE,
  },
  {
    id: "5",
    name: "CBR1000RR",
    brand: "Honda",
    reviews: 4,
    originalPrice: 21000,
    currentPrice: 20000,
    image: getImageUrl("5"),
    category: ProductCategory.MOTORCYCLE,
    discount: 25,
  },
  {
    id: "6",
    name: "GSX-R1000",
    brand: "Suzuki",
    reviews: 4,
    originalPrice: 19000,
    currentPrice: 18000,
    image: getImageUrl("6"),
    category: ProductCategory.MOTORCYCLE,
  },
  {
    id: "66",
    name: "GSX-R1065",
    brand: "Suzuki",
    reviews: 5,
    originalPrice: 22000,
    currentPrice: 17000,
    image: getImageUrl("66"),
    category: ProductCategory.MOTORCYCLE,
  },
  // Loans
  {
    id: "7",
    name: "Personal Loan",
    brand: "Banco de Chile",
    reviews: 3,
    originalPrice: 10000,
    currentPrice: 9900,
    image: getImageUrl("7"),
    category: ProductCategory.LOAN,
    discount: 30,
  },
  {
    id: "8",
    name: "Auto Loan",
    brand: "Banco Estado",
    reviews: 4,
    originalPrice: 15000,
    currentPrice: 14500,
    image: getImageUrl("8"),
    category: ProductCategory.LOAN,
    discount: 45,
  },
  {
    id: "88",
    name: "Auto Loan Premium",
    brand: "Banco Estado",
    reviews: 4,
    originalPrice: 18000,
    currentPrice: 13500,
    image: getImageUrl("88"),
    category: ProductCategory.LOAN,
  },
  {
    id: "77",
    name: "Auto Loan Premium Plus",
    brand: "Banco Estado",
    reviews: 4,
    originalPrice: 13000,
    currentPrice: 10500,
    image: getImageUrl("77"),
    category: ProductCategory.LOAN,
    discount: 50,
  },
  // Stores
  {
    id: "9",
    name: "Falabella Online",
    brand: "Falabella",
    reviews: 4,
    originalPrice: 500,
    currentPrice: 450,
    image: getImageUrl("9"),
    category: ProductCategory.STORE,
  },
  {
    id: "10",
    name: "Paris Mall",
    brand: "Paris",
    reviews: 5,
    originalPrice: 600,
    currentPrice: 550,
    image: getImageUrl("10"),
    category: ProductCategory.STORE,
    discount: 15,
  },
  {
    id: "100",
    name: "Paris Mall 2",
    brand: "Paris",
    reviews: 5,
    originalPrice: 6000,
    currentPrice: 4500,
    image: getImageUrl("100"),
    category: ProductCategory.STORE,
    discount: 30,
  },
  {
    id: "110",
    name: "Paris Jardin Mall",
    brand: "Paris",
    reviews: 5,
    originalPrice: 600,
    currentPrice: 550,
    image: getImageUrl("110"),
    category: ProductCategory.STORE,
  },
  // Tracking
  {
    id: "11",
    name: "Express Delivery",
    brand: "Correos de Chile",
    reviews: 3,
    originalPrice: 50,
    currentPrice: 45,
    image: getImageUrl("11"),
    category: ProductCategory.TRACKING,
    discount: 45,
  },
  {
    id: "12",
    name: "Priority Shipping",
    brand: "Chilexpress",
    reviews: 4,
    originalPrice: 60,
    currentPrice: 55,
    image: getImageUrl("12"),
    category: ProductCategory.TRACKING,
  },
  {
    id: "122",
    name: "Priority Shipping Express",
    brand: "Chilexpress",
    reviews: 4,
    originalPrice: 660,
    currentPrice: 555,
    image: getImageUrl("122"),
    category: ProductCategory.TRACKING,
    discount: 45,
  },
  {
    id: "125",
    name: "Priority Shipping",
    brand: "Chilexpress",
    reviews: 4,
    originalPrice: 670,
    currentPrice: 455,
    image: getImageUrl("125"),
    category: ProductCategory.TRACKING,
    discount: 45,
  },

  // Clubs
  {
    id: "13",
    name: "Cencosud Club",
    brand: "Cencosud",
    reviews: 5,
    originalPrice: 100,
    currentPrice: 90,
    image: getImageUrl("13"),
    category: ProductCategory.CLUB,
    discount: 45,
  },
  {
    id: "14",
    name: "Paris Club",
    brand: "Paris",
    reviews: 4,
    originalPrice: 120,
    currentPrice: 110,
    image: getImageUrl("14"),
    category: ProductCategory.CLUB,
  },
  {
    id: "15",
    name: "Liverpool Club",
    brand: "Liverpool",
    reviews: 3,
    originalPrice: 130,
    currentPrice: 120,
    image: getImageUrl("15"),
    category: ProductCategory.CLUB,
  },
  {
    id: "155",
    name: "Liverpool Club Plus",
    brand: "Liverpool",
    reviews: 3,
    originalPrice: 130,
    currentPrice: 120,
    image: getImageUrl("155"),
    category: ProductCategory.CLUB,
    discount: 45,
  },
];

export const carouselImages = [
  {
    id: "5",
    image: "https://picsum.photos/seed/5/1639/700",
    alt: `Carousel image 5`,
  },
  {
    id: "6",
    image: "https://picsum.photos/seed/6/1639/700",
    alt: `Carousel image 6`,
  },
  {
    id: "7",
    image: "https://picsum.photos/seed/7/1639/700",
    alt: `Carousel image 7`,
  },
];
